// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bgeyyywuekyukyzqzxoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnZXl5eXd1ZWt5dWt5enF6eG9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2OTY0NDAsImV4cCI6MjA4NTI3MjQ0MH0.wKwHCOPKhLKH3LlWLA6H6Po_Aw7vASZT1FEIpKkulP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);